project:
  type: website

website:
  title: "VABI Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: proposal.qmd
        text: Proposal
      - href: methodology.qmd
        text: Data Wrangling
      - href: visual-analytics-story.qmd
        text: Visual Analytics Story

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true